version: '3.7'

services:
  meta-broker:
    build: .
    container_name: meta-broker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

volumes:
  data:
  logs: 